[package]
name = "chimera-desktop"
version.workspace = true
edition.workspace = true

[dependencies]
chimera-core = { path = "../chimera-core" }
chimera-hal = { path = "../chimera-hal" }
libm = "0.2"
minifb = "0.28"
cpal = "0.15"
midir = "0.10"
embedded-graphics = "0.8"
embedded-graphics-core = "0.4"
